Goal: Create a Risk Factor Model using PCA

Chosen portfolio: S&P500



```{r}
#download packages
library(tidyquant) #https://business-science.github.io/tidyquant/
library(tidyverse) #https://tidyverse.org/
library(Matrix)    #https://codeberg.org/jaganmn/Matrix
```

```{r}
#download index of s&p500
basket <- tq_index("S&P500")
```

```{r}
head(basket)
write.csv(basket, "sp500_basket.csv", row.names = FALSE)
```

```{r}
#clean the dataframe
df <- read_csv("sp500_basket.csv")

colSums(is.na(df))
colSums(df == "" | df == " " | df == "-", na.rm = TRUE)

df_clean <- df |>
  mutate(sector = na_if(sector, ""),
         sector = na_if(sector, "-"))
df_clean$sector <- NULL

head(df_clean)
```

```{r}
#the current data set is for right now. I need historical returns from last 10 years such that I cover a full business cycle, and have enough data for PCA. get daily close price and then convert into % daily change

tickers <- df_clean |>
  mutate(symbol = str_replace_all(symbol, "\\.", "-")) |> #need to replace . with - so yfinance can read (BRK.B for ex)
  pull(symbol) |> #create vector
  unique() #make sure no duplicates

#get the data. 500 tickers is a lot. make a saved file so don't need to call yfinance everytime. use .rds bc faster than .csv and keeps data types. 
if (!file.exists("sp500_prices.rds")) 
    { 
    historical_prices <- tq_get(tickers,
                get  = "stock.prices",
                from = Sys.Date() - years(10),
                to   = Sys.Date())
    saveRDS(historical_prices, "sp500_prices.rds") #save the data so don't need to re-do each time (caching = efficiency)
    } else 
        {
        historical_prices <- readRDS("sp500_prices.rds")
        }
if (!file.exists("sp500_prices.csv"))
    {
    historical_prices <- write_csv(historical_prices, "sp500_prices.csv") #for human readability
    }
head(historical_prices)
```


```{r}
#create covariance matrix
returns <- historical_prices |>
  group_by(symbol) |>
  arrange(date, .by_group = TRUE) |>
  mutate(ret = adjusted / lag(adjusted) - 1) |> #DoD price return
  ungroup() |>
  filter(!is.na(ret)) |>
  select(date, symbol, ret)

returns_wide <- returns |>
  pivot_wider(names_from = symbol, values_from = ret) |>
  arrange(date)

#keep stocks with >= 98% of days in the 10yr window --> 10 years bc approx. 1 business cycle
coverage <- colMeans(!is.na(select(returns_wide, -date))) 
keep <- names(coverage)[coverage >= 0.98]
returns_wide <- returns_wide |>
    select(date, all_of(keep)) |>
    drop_na()

#use matrix naming convention: A for return matrix
A <- as.matrix(select(returns_wide, -date))
rownames(A) <- as.character(returns_wide$date)
head(A) 

split   <- floor(0.8 * nrow(A))
A_train <- A[1:split, ]
A_test  <- A[(split + 1):nrow(A), ]

#now calculate the cov() 
#mean of each column: xbar_j = sum(x_j) / n
xbar = colMeans(A_train)
#deviation from the mean: y_j = x_j - xbar_j
dev <- sweep(A_train, 2, xbar)
#diagonal (variance): y_i * y_j   = y_i^2 --> since diagonal y_i = y_j so y_i * y_j = y_i * y_i = y_i^2
#off-diagonal (covariance): y_i * y_j --> y_i != y_j here
#sum over days, divide by n-1:  SUM_ij = [sum(y_i * y_j) / (n - 1)]
cov_A <- t(dev) %*% dev / (nrow(dev) - 1) 
#where t(dev) is the transpose: TxN --> NxT, %*% is matrix multiplication

all.equal(cov_A, cov(A_train)) #this needs to be true to make sure I did the above right.
```

```{r}
#set up the components

#cov() to corr(): sd = sqrt(variance) --> sigma vs sigma^2
#only want the variance => diagonal of the matrix. rest is covariance
stdev_A <- sqrt(diag(cov_A)) 

```

```{r}
#create the model
```